### ISSUE TITLE
Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by Orygeunik** [ewewukek/mc-musketmod#20]
Hello! I have some problem when using this mod

In singleplayer server (Creative mode) (fabric version, world type Amplified) after shot i was received the following error (with logout into main menu):

```
[21:22:58] [Netty Local Client IO #0/ERROR]: Thread dumps: 
Netty Local Client IO #0: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.class_5798.method_39936(class_5798.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.class_5798.method_33564(class_5798.java:82)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:33)
	at net.minecraft.class_761.method_3268(class_761.java:2790)
	at net.minecraft.class_761.method_3288(class_761.java:2760)
	at net.minecraft.class_761.method_8563(class_761.java:2731)
	at net.minecraft.class_761.method_8568(class_761.java:2726)
	at net.minecraft.class_638.method_8406(class_638.java:607)
	at ewewukek.musketmod.GunItem.fireParticles(GunItem.java:242)
	at ewewukek.musketmod.ClientSetup.lambda$onInitializeClient$2(ClientSetup.java:29)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:97)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:39)
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:89)
	at net.minecraft.class_634.handler$bgn000$handleCustomPayload(class_634.java:2522)
	at net.minecraft.class_634.method_11152(class_634.java)
	at net.minecraft.class_2658.method_11457(class_2658.java:60)
	at net.minecraft.class_2658.method_11054(class_2658.java:8)
	at net.minecraft.class_2535.method_10759(class_2535.java:167)
	at net.minecraft.class_2535.method_10770(class_2535.java:152)
	at net.minecraft.class_2535.channelRead0(class_2535.java:50)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)

[21:22:58] [Netty Local Client IO #0/ERROR]: Encountered exception while handling in channel with name "musketmod:smoke_effect"
net.minecraft.class_148: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.class_761.method_8563(class_761.java:2740) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_8568(class_761.java:2726) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_8406(class_638.java:607) ~[client-intermediary.jar:?]
	at ewewukek.musketmod.GunItem.fireParticles(GunItem.java:242) ~[musketmod-1.19.2-fabric-1.4.4.jar:?]
	at ewewukek.musketmod.ClientSetup.lambda$onInitializeClient$2(ClientSetup.java:29) ~[musketmod-1.19.2-fabric-1.4.4.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:97) ~[fabric-networking-api-v1-1.2.5+c6af733c90-ec866652fb51a93a.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:39) ~[fabric-networking-api-v1-1.2.5+c6af733c90-ec866652fb51a93a.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) [fabric-networking-api-v1-1.2.5+c6af733c90-ec866652fb51a93a.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:89) [fabric-networking-api-v1-1.2.5+c6af733c90-ec866652fb51a93a.jar:?]
	at net.minecraft.class_634.handler$bgn000$handleCustomPayload(class_634.java:2522) [client-intermediary.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) [client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) [client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:167) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:152) [client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:50) [client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.class_5798.method_33564(class_5798.java:84) ~[client-intermediary.jar:?]
	at net.minecraft.class_5820.method_43156(class_5820.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.class_6566.method_43048(class_6566.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3268(class_761.java:2790) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3288(class_761.java:2760) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_8563(class_761.java:2731) ~[client-intermediary.jar:?]
	... 32 more

```

Used mods:
```
	- advanced_runtime_resource_pack 0.6.4
	- ae2 12.8.2-beta
	- ae2wtlib 12.7.0
	- appleskin 2.4.1+mc1.19
	- architectury 6.2.46
	- armorrenderlib 0.2.6 via relicex
	- attributefix 17.1.3
	- autopath 1.4.9
	- badpackets 0.2.0
	- basicshields 1.4.0-pre2-1.19.2
	- betteradvancements 0.2.2.142
	- betterdroppeditems 1.4.1-1.19
	- betterfpsdist 1.19.1-1.9
	- blockus 2.5.2+1.19.2
	- blue_endless_jankson 1.2.1 via owo
	- bookshelf 16.1.6
	- botanypots 9.0.7
	- botanytrees 5.0.1
	- cacao 1.2
	- cardinal-components-base 5.0.2 via playerex
	- cardinal-components-block 5.0.1 via polymorph
	- cardinal-components-entity 5.0.2 via playerex
	- cardinal-components-item 5.0.1 via polymorph
	- charmofundying 6.0.0+1.19.2
	- chisel 1.4.6
	- clear-skies 2.0.95
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.1.77 via fabricshieldlib
	- clumps 9.0.0+11
	- columns 1.5.1
	- com_electronwill_night-config_core 3.6.5 via couplings
	- com_electronwill_night-config_toml 3.6.5 via couplings
	- com_eliotlash_mclib_mclib 19 via geckolib3
	- com_eliotlash_molang_molang 19 via geckolib3
	- com_github_llamalad7_mixinextras 0.0.12 via debugify
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- com_typesafe_config 1.4.1 via croptopia
	- consistency_plus 0.5.1+1.19.2
	- continuity 2.0.1+1.19
	- couplings 1.9.1+1.19
	- croptopia 2.1.0
	- crowdin-translate 1.4+1.19 via basicshields
	- dataattributes 1.2.7
	- debugify 2.7.1
	- decorative_blocks 3.0.0
	- dehydration 1.3.1
	- detailab 2.6.2+1.19-fabric
	- dynamicfps 2.2.0
	- editsign 2.6.0
	- elytraslot 6.0.0+1.19.2
	- enchant_giver 1.3.0 via mcdw
	- enchdesc 13.0.6
	- entityculling 1.5.2-mc1.19
	- equipmentcompare 1.3.1
	- error_notifier 1.0.9 via roughlyenoughitems
	- fabric-api 0.62.0+1.19.2
	- fabric-api-base 0.4.12+93d8cb8290 via fabric-api
	- fabric-api-lookup-api-v1 1.6.10+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.0.18+c6af733c90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.21+c6af733c90 via fabric-api
	- fabric-client-tags-api-v1 1.0.2+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.12+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.8+93d8cb8290 via fabric-api
	- fabric-commands-v0 0.2.29+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.35+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.3.1+624e468e90 via fabric-api
	- fabric-convention-tags-v1 1.1.2+93d8cb8290 via fabric-api
	- fabric-crash-report-info-v1 0.2.6+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.2.0+b598f4ac90 via fabric-api
	- fabric-dimensions-v1 2.1.32+0dd10df690 via fabric-api
	- fabric-entity-events-v1 1.4.19+9ff28f4090 via fabric-api
	- fabric-events-interaction-v0 0.4.29+c6af733c90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.29+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.22+c6af733c90 via fabric-api
	- fabric-item-api-v1 1.5.8+93d8cb8290 via fabric-api
	- fabric-item-groups-v0 0.3.30+93d8cb8290 via fabric-api
	- fabric-key-binding-api-v1 1.0.21+93d8cb8290 via fabric-api
	- fabric-keybindings-v0 0.2.19+df3654b390 via fabric-api
	- fabric-language-kotlin 1.8.4+kotlin.1.7.20
	- fabric-lifecycle-events-v1 2.2.0+33ffe9ec90 via fabric-api
	- fabric-loot-api-v2 1.1.4+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.7+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.4+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.15+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.18+c6af733c90 via fabric-api
	- fabric-networking-api-v1 1.2.5+c6af733c90 via fabric-api
	- fabric-networking-v0 0.3.22+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.0.12+93d8cb8290 via fabric-api
	- fabric-particles-v1 1.0.11+79adfe0a90 via fabric-api
	- fabric-registry-sync-v0 0.9.26+c6af733c90 via fabric-api
	- fabric-renderer-api-v1 1.0.11+c6af733c90 via fabric-api
	- fabric-renderer-indigo 0.6.13+aeb40ebe90 via fabric-api
	- fabric-renderer-registries-v1 3.2.21+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.15+aeb40ebe90 via fabric-api
	- fabric-rendering-fluids-v1 3.0.8+c6af733c90 via fabric-api
	- fabric-rendering-v0 1.1.23+df3654b390 via fabric-api
	- fabric-rendering-v1 1.11.0+73145abb90 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.12+a29562c890 via fabric-api
	- fabric-resource-loader-v0 0.7.0+93d8cb8290 via fabric-api
	- fabric-screen-api-v1 1.0.27+93d8cb8290 via fabric-api
	- fabric-screen-handler-api-v1 1.3.1+1cc24b1b90 via fabric-api
	- fabric-textures-v0 1.0.21+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.1.1+93d8cb8290 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.1+42d99c3290 via fabric-api
	- fabricloader 0.14.9
	- fabricshieldlib 1.6.0-1.19
	- fake-player-api 0.4.0 via indrev
	- fallingleaves 1.12.2+1.19.2
	- fallingtree 3.9.2
	- farsight 1.19-2.1
	- fiber 0.23.0-2 via patchouli
	- forgeconfigapiport 4.2.6
	- fwaystones 3.0.5+mc1.19.2
	- geckolib3 3.1.23
	- glassdoor 3.1.0-beta.1+1.19
	- graveyard 2.0
	- grindenchantments 2.0.0-beta.2+1.19.2
	- iceberg 1.0.46
	- imm_ptl_core 2.2.5 via immersive_portals
	- immersive_portals 2.2.5
	- imst 2.0.3
	- indium 1.0.9+mc1.19.2
	- indrev 1.15.1-BETA
	- inventoryhud 3.4.2
	- inventoryprofilesnext 1.8.2
	- io_github_douira_glsl-transformer 1.0.0-pre21.2 via iris
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- iris 1.4.0
	- ironchests 1.7.7
	- jankson 4.1.1+j1.2.1 via libgui
	- java 17
	- lambdabettergrass 1.3.0+1.19
	- lambdynlights 2.1.2+1.19
	- lazydfu 0.1.3
	- libgui 6.2.0+1.19 via ironchests
	- libipn 1.0.3
	- libninepatch 1.1.0 via libgui
	- lithium 0.9.1
	- magna 1.8.0-1.19 via modern_industrialization
	- mcda 2.2.0
	- mcdar 1.5.2-1.19
	- mcdw 5.0.4-1.19
	- mcwbridges 2.0.5
	- mcwdoors 1.0.7
	- mcwfences 1.0.6
	- mcwlights 1.0.4
	- mcwtrpdoors 1.0.7
	- mcwwindows 2.0.3
	- medievalweapons 1.4.1
	- megane 8.3.0
	- megane-api 8.3.0 via megane
	- megane-applied-energistics-2 8.3.0 via megane
	- megane-fabric-transfer 8.3.0 via megane
	- megane-industrial-revolution 8.3.0 via megane
	- megane-reborn-core 8.3.0 via megane
	- megane-reborn-energy 8.3.0 via megane
	- megane-runtime 8.3.0 via megane
	- megane-tech-reborn 8.3.0 via megane
	- megane-vanilla 8.3.0 via megane
	- minecraft 1.19.2
	- mm 2.3 via fabricshieldlib
	- modelfix 1.8
	- modern_industrialization 1.3.2
	- modmenu 4.0.6
	- moonlight 1.19.2-2.0.37
	- musketmod 1.4.4
	- mvs 2.5.9
	- nameplate 1.0.9
	- net_objecthunter_exp4j 0.4.8 via playerex
	- noindium 1.1.0+1.19 via ae2
	- omega-config 1.2.2-1.18.1 via graveyard
	- opc 0.6.4 via playerex
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.10.1 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- owo 0.8.5+1.19
	- particlerain 2.0.0
	- patchouli 1.19.2-76-FABRIC
	- phosphor 0.8.1
	- placeholder-api 2.0.0-beta.7+1.19 via playerex
	- playerabilitylib 1.6.0 via modern_industrialization
	- playerex 3.3.7
	- polymorph 0.45.0+1.19.2
	- pride 1.1.2+1.19 via lambdynlights
	- q_misc_util 2.2.5 via immersive_portals
	- quarrymod 1.0.2
	- reach-entity-attributes 2.3.0 via mcdw
	- reborncore 5.3.4 via techreborn
	- redstonepen 1.2.18
	- relicex 3.2.5
	- roughlyenoughitems 9.1.550
	- roughlyenoughresources 2.6.0
	- rpgdifficulty 1.2.2
	- smoothchunk 1.19.1-2.0
	- sodium 0.4.4+build.18
	- spruceui 4.0.0+1.19 via lambdabettergrass
	- step-height-entity-attribute 1.0.0 via indrev
	- stonecutter_recipe_tags 4.0.0+1.19.9b8d04c.fabric via consistency_plus
	- supplementaries 1.19.2-2.2.6
	- team_reborn_energy 2.2.0 via modern_industrialization
	- techreborn 5.3.4
	- terraform-wood-api-v1 4.1.0 via blockus
	- toolleveling 1.19.2-1.4.1
	- trinkets 3.4.0
	- wthit 5.13.1
	- xaerominimap 22.16.0
	- xaeroworldmap 1.28.1
	- xps 0.4.6-r+1.19.2-Fabric
	- yet-another-config-lib 1.5.0
```

**Comment by Orygeunik** [comment]
I find some bug report
https://bugs.mojang.com/browse/MC-250118

**Comment by ewewukek** [comment]
should be fixed now

**Comment by Orygeunik** [comment]
Sorry, but with version `musketmod 1.4.5 (musketmod-1.19.2-fabric-1.4.5.jar)`

Problem still exist

```
[09:12:43] [Netty Local Client IO #0/ERROR]: Thread dumps: 
Netty Local Client IO #0: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.class_5798.method_39936(class_5798.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.class_5798.method_33564(class_5798.java:82)
	at net.minecraft.class_5820.method_43156(class_5820.java:49)
	at net.minecraft.class_6566.method_43048(class_6566.java:33)
	at net.minecraft.class_761.method_3268(class_761.java:2790)
	at net.minecraft.class_761.method_3288(class_761.java:2760)
	at net.minecraft.class_761.method_8563(class_761.java:2731)
	at net.minecraft.class_761.method_8568(class_761.java:2726)
	at net.minecraft.class_638.method_8406(class_638.java:607)
	at ewewukek.musketmod.GunItem.fireParticles(GunItem.java:244)
	at ewewukek.musketmod.ClientSetup.lambda$onInitializeClient$2(ClientSetup.java:29)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:97)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:39)
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:89)
	at net.minecraft.class_634.handler$bgo000$handleCustomPayload(class_634.java:2522)
	at net.minecraft.class_634.method_11152(class_634.java)
	at net.minecraft.class_2658.method_11457(class_2658.java:60)
	at net.minecraft.class_2658.method_11054(class_2658.java:8)
	at net.minecraft.class_2535.method_10759(class_2535.java:167)
	at net.minecraft.class_2535.method_10770(class_2535.java:152)
	at net.minecraft.class_2535.channelRead0(class_2535.java:50)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)

[09:12:43] [Netty Local Client IO #0/ERROR]: Encountered exception while handling in channel with name "musketmod:smoke_effect"
net.minecraft.class_148: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.class_761.method_8563(class_761.java:2740) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_8568(class_761.java:2726) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_8406(class_638.java:607) ~[client-intermediary.jar:?]
	at ewewukek.musketmod.GunItem.fireParticles(GunItem.java:244) ~[musketmod-1.19.2-fabric-1.4.5.jar:?]
	at ewewukek.musketmod.ClientSetup.lambda$onInitializeClient$2(ClientSetup.java:29) ~[musketmod-1.19.2-fabric-1.4.5.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:97) ~[fabric-networking-api-v1-1.2.5+c6af733c90-5612b0fd8966152f.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:39) ~[fabric-networking-api-v1-1.2.5+c6af733c90-5612b0fd8966152f.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) [fabric-networking-api-v1-1.2.5+c6af733c90-5612b0fd8966152f.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:89) [fabric-networking-api-v1-1.2.5+c6af733c90-5612b0fd8966152f.jar:?]
	at net.minecraft.class_634.handler$bgo000$handleCustomPayload(class_634.java:2522) [client-intermediary.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) [client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) [client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:167) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:152) [client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:50) [client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.class_5798.method_33564(class_5798.java:84) ~[client-intermediary.jar:?]
	at net.minecraft.class_5820.method_43156(class_5820.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.class_6566.method_43048(class_6566.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3268(class_761.java:2790) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3288(class_761.java:2760) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_8563(class_761.java:2731) ~[client-intermediary.jar:?]
	... 32 more
```

**Comment by ewewukek** [comment]
i think i found what mod was doing wrong. please test this version
https://ewewukek.me/tmp/448607163cf61e8c517ea7315176a39041d588b6/musketmod-1.19.2-fabric-1.4.6.jar

**Comment by Orygeunik** [comment]
> i think i found what mod was doing wrong. please test this version https://ewewukek.me/tmp/448607163cf61e8c517ea7315176a39041d588b6/musketmod-1.19.2-fabric-1.4.6.jar

yeap, problem fixed, thanks
